- name: variable
  hosts: local
  connection: local
  tasks:
  - name: printing the variable
    ansible.builtin.debug:
      msg: "Course is Devops with aws, Duration is 120hrs, Trainer is Manikanta"
  