- name: variables
  hosts: local
  connection: local
  vars: #Play Level Variables, gloabal variables
    Course: "DevOps with AWS"
    Duration: "120hrs"
    Trainer: "Sri Manikanta"
  tasks:
  - name: printing the variable
    vars: # Taks level variables, accesible only with in the task only. Task level variable override the playlevel variables.
      Course: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ Course }}, Duration is {{ Duration }}, Trainer is {{ Trainer }}"

  - name: printing the variable
    ansible.builtin.debug:
      msg: "Course is {{ Course }}, Duration is {{ Duration }}, Trainer is {{ Trainer }}"

