- name: variable
  hosts: local
  connection: local
  vars:
    Course: "DevOps"
    Duration: "12hrs"
    Trainer: "Sri Manikanta"
  tasks:
  - name: printing the variable
    vars:  #Task level variables
      Course: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ Course }}, Duration is {{ Duration }}, Trainer is {{ Trainer }}"

   
  - name: printing the variable
    ansible.builtin.debug:
      msg: "Course is {{ Course }}, Duration is {{ Duration }}, Trainer is {{ Trainer }}"