- name: varibales form files
  hosts: local
  connection: local
  vars_files: 
  - course.yaml

  tasks:
  - name: print course information
    anisble.builtin.debug:
      msg: "Course is {{ COURSE }, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
