- name: variable
  hosts: local
  connection: local
  tasks:
  - name: printing the variable
    ansible.builtin.debug:
      msg: "COURSE is {{ Course }}, DURATION is {{ Duration }}, TRAINER is {{ Trainer }}"