- name: loops
  hosts: local
  connection: local

  tasks:
    - name: print the msgs
      ansible.builtin.debug:
        msg: "{{ item }}"

      loop:
        - gcc
        - git
        - mysql
        - zip