- name: filters
  hosts: local
  connection: local

  tasks:

    - name: Handle undefined variables
      ansible.builtin.debug:
        msg: "Hello {{ person | default('Ramesh') }}"

    - name: convert string to list
      vars:
        fruits: "apple, banana, orange"

      ansible.builtin.debug:
        msg: "Fruits are: {{ fruits | split(',') }}"

    - name: convert map into list
      vars:
        course:
          name: ansible
          duration: 10hrs
          trainer: manikanta

      ansible.builtin.debug:
        msg: "Course info: {{ course | dict2items }}"

    - name: convert list into map
      vars:
        course:
          - { name: 'gcc', state: 'present' }
          - { name: 'mysql', state: 'absent' }
          - { name: 'git', state: 'present' }
          - { name: 'zip', state: 'absent' }

      ansible.builtin.debug:
        msg: "Course info: {{ course | items2dict(key_name='name', value_name='state') }}"


    - name: convert upper to lower
      vars:
        name: "Sri Manikanta A"
      ansible.builtin.debug:
        msg: "Hello {{ name | lower }}"

    
    - name: convert lower to upper
      vars:
        name: "Sri Manikanta A"
      ansible.builtin.debug:
        msg: "Hello {{ name | upper }}"
    
    - name: print min and max
  vars:
    numbers: [1,30,57,87,98,46845]
  ansible.builtin.debug:
    msg: "Min is: {{ numbers | min }}, Max is: {{ numbers | max }}"

- name: check ipaddress is valid or not
  vars:
    ip: "256.255.245.256"
  ansible.builtin.debug:
    msg: "{{ ip | ansible.utils.ipaddr }}"
