[local]  #Group Name
localhost #Current Machine


[web]
172.31.73.36


# 172.31.73.36 COURSE="DevOps with AWS" TRAINER="Sri Manikanta" DURATION="12hrs" ansible_user=ec2-user ansible_password=DevOps321
# localhost COURSE="Ansible" TRAINER="Chintu" DURATION="12hrs" ansible_user=ec2-user ansible_password=DevOps321




[local:vars]
COURSE="Devops"
DURATION="12hrs"
TRAINER="Chintu"